<a href="https://colab.research.google.com/github/Neermita18/Spatial_gene_enhancement_bio_intern/blob/main/Neermita.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Allen_VISp, STARMap

In [3]:
pip install stPlus

Collecting stPlus
  Downloading stPlus-0.0.6-py3-none-any.whl (8.1 kB)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from stPlus) (2.3.0+cu121)
Requirement already satisfied: torchvision>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from stPlus) (0.18.0+cu121)
Requirement already satisfied: pandas>=1.1.0b in /usr/local/lib/python3.10/dist-packages (from stPlus) (2.0.3)
Requirement already satisfied: numpy>=1.19.1 in /usr/local/lib/python3.10/dist-packages (from stPlus) (1.25.2)
Requirement already satisfied: scipy>=1.5.2 in /usr/local/lib/python3.10/dist-packages (from stPlus) (1.11.4)
Requirement already satisfied: scikit-learn>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from stPlus) (1.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0b->stPlus) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0b->stPlus) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0b->stPlus) (2024.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23.2->stPlus) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.23.2->stPlus) (3.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->stPlus) (3.15.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->stPlus) (4.12.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->stPlus) (1.12.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->stPlus) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->stPlus) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->stPlus) (2023.6.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch>=1.6.0->stPlus)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch>=1.6.0->stPlus)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch>=1.6.0->stPlus)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch>=1.6.0->stPlus)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/nvidia-cublas-cu12/
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch>=1.6.0->stPlus)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch>=1.6.0->stPlus)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch>=1.6.0->stPlus)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch>=1.6.0->stPlus)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch>=1.6.0->stPlus)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch>=1.6.0->stPlus)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch>=1.6.0->stPlus)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->stPlus) (2.3.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.6.0->stPlus)
  Downloading nvidia_nvjitlink_cu12-12.5.40-py3-none-manylinux2014_x86_64.whl (21.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 39.5 MB/s eta 0:00:00
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision>=0.7.0->stPlus) (9.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.0b->stPlus) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->stPlus) (2.1.5)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->stPlus) (1.3.0)
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, stPlus
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.40 nvidia-nvtx-cu12-12.1.105 stPlus-0.0.6

In [4]:
import stPlus

/usr/local/lib/python3.10/dist-packages/torch/__init__.py:747: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:431.)
  _C._set_default_tensor_type(t)

In [5]:
pip install scanpy

Collecting scanpy
  Downloading scanpy-1.10.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 9.6 MB/s eta 0:00:00
Collecting anndata>=0.8 (from scanpy)
  Downloading anndata-0.10.8-py3-none-any.whl (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.4/124.4 kB 10.9 MB/s eta 0:00:00
Requirement already satisfied: h5py>=3.1 in /usr/local/lib/python3.10/dist-packages (from scanpy) (3.9.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from scanpy) (1.4.2)
Collecting legacy-api-wrap>=1.4 (from scanpy)
  Downloading legacy_api_wrap-1.4-py3-none-any.whl (15 kB)
Requirement already satisfied: matplotlib>=3.6 in /usr/local/lib/python3.10/dist-packages (from scanpy) (3.7.1)
Requirement already satisfied: natsort in /usr/local/lib/python3.10/dist-packages (from scanpy) (8.4.0)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.10/dist-packages (from scanpy) (3.3)
Requirement already satisfied: numba>=0.56 in /usr/local/lib/python3.10/dist-packages (from scanpy) (0.58.1)
Requirement already satisfied: numpy<2,>=1.23 in /usr/local/lib/python3.10/dist-packages (from scanpy) (1.25.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from scanpy) (24.1)
Requirement already satisfied: pandas>=1.5 in /usr/local/lib/python3.10/dist-packages (from scanpy) (2.0.3)
Requirement already satisfied: patsy in /usr/local/lib/python3.10/dist-packages (from scanpy) (0.5.6)
Collecting pynndescent>=0.5 (from scanpy)
  Downloading pynndescent-0.5.13-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.9/56.9 kB 7.5 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn>=0.24 in /usr/local/lib/python3.10/dist-packages (from scanpy) (1.2.2)
Requirement already satisfied: scipy>=1.8 in /usr/local/lib/python3.10/dist-packages (from scanpy) (1.11.4)
Requirement already satisfied: seaborn>=0.13 in /usr/local/lib/python3.10/dist-packages (from scanpy) (0.13.1)
Collecting session-info (from scanpy)
  Downloading session_info-1.0.0.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: statsmodels>=0.13 in /usr/local/lib/python3.10/dist-packages (from scanpy) (0.14.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from scanpy) (4.66.4)
Collecting umap-learn!=0.5.0,>=0.5 (from scanpy)
  Downloading umap_learn-0.5.6-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 7.4 MB/s eta 0:00:00
Collecting array-api-compat!=1.5,>1.4 (from anndata>=0.8->scanpy)
  Downloading array_api_compat-1.7.1-py3-none-any.whl (37 kB)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anndata>=0.8->scanpy) (1.2.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6->scanpy) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6->scanpy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6->scanpy) (4.53.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6->scanpy) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6->scanpy) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6->scanpy) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.6->scanpy) (2.8.2)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba>=0.56->scanpy) (0.41.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->scanpy) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.5->scanpy) (2024.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.24->scanpy) (3.5.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy->scanpy) (1.16.0)
Collecting stdlib_list (from session-info->scanpy)
  Downloading stdlib_list-0.10.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 9.8 MB/s eta 0:00:00
Building wheels for collected packages: session-info
  Building wheel for session-info (setup.py) ... done
  Created wheel for session-info: filename=session_info-1.0.0-py3-none-any.whl size=8026 sha256=eed535813fccddd044df197e924a4339de566d303e20ebbd76965b8a2c3634c6
  Stored in directory: /root/.cache/pip/wheels/6a/aa/b9/eb5d4031476ec10802795b97ccf937b9bd998d68a9b268765a
Successfully built session-info
Installing collected packages: array-api-compat, stdlib_list, legacy-api-wrap, session-info, pynndescent, anndata, umap-learn, scanpy
Successfully installed anndata-0.10.8 array-api-compat-1.7.1 legacy-api-wrap-1.4 pynndescent-0.5.13 scanpy-1.10.2 session-info-1.0.0 stdlib_list-0.10.0 umap-learn-0.5.6

In [2]:
import numpy as np
import pandas as pd
import scanpy as sc

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
spatial_csv=pd.read_csv('/content/drive/MyDrive/scDatsets/STARmap_data_scvi.csv')

In [9]:
spatial_csv

,Unnamed: 0,1110008F13Rik,1110008P14Rik,1700019D03Rik,1700086L19Rik,2810468N07Rik,2900055J20Rik,2900092D14Rik,3110035E14Rik,3632451O06Rik,...,Zcchc12,Zdhhc24,Zfand6,Zfp57,Zfp637,Zfp975,Zmat4,Zmym1,Znhit3,Znrd1
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,1544,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1545,1545,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1546,1546,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0
1547,1547,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
1548,1548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0

In [10]:
genes_csv=pd.read_csv('/content/drive/MyDrive/scDatsets/genes.csv', header=None)

In [11]:
genes_csv

                  0        1
0     1110008F13Rik  CAATTTC
1     1110008P14Rik  CCAATGC
2     1700019D03Rik  CTCGCAC
3     1700086L19Rik  CAACTTC
4     2810468N07Rik  CAAAAAC
...             ...      ...
1015         Zfp975  CCGAAAC
1016          Zmat4  CTTCGAC
1017          Zmym1  CCATAGC
1018         Znhit3  CGAGGTC
1019          Znrd1  CCTGCCC

[1020 rows x 2 columns]

In [12]:
classes=pd.read_csv('/content/drive/MyDrive/scDatsets/class_labels.csv')

In [13]:
classes

      CellID  ClusterID ClusterName
0          0         -1         NaN
1          1         -1         NaN
2          2         -1         NaN
3          3         -1         NaN
4          4         -1         NaN
...      ...        ...         ...
1384    1384          8         eL4
1385    1385         -1         NaN
1386    1386          5         Smc
1387    1387         -1         NaN
1388    1388          5     Astro-2

[1389 rows x 3 columns]

In [14]:
cell_barcodes= pd.read_csv('/content/drive/MyDrive/scDatsets/cell_barcode_count.csv', header=None)

In [15]:
cell_barcodes

,0,1,2,3,4,5,6,7,8,9,...,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1545,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1546,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,1
1547,0,0,1,0,1,0,0,0,0,0,...,0,0,1,0,3,0,0,0,0,0
1548,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,0,0,0,0,0

In [16]:
centroids=pd.read_csv('/content/drive/MyDrive/scDatsets/centroids.tsv', header=None, sep='\t')

In [17]:
centroids

                0             1
0       19.918240   1951.627361
1       27.798811   2969.047719
2       26.733311   2804.845522
3       24.085884   8867.800070
4       26.384918  10853.262078
...           ...           ...
1544  7068.752534   2011.076655
1545  7054.579261   1114.177633
1546  7079.605451   2926.862652
1547  7069.509113   9165.649339
1548  7068.738341  10991.187546

[1549 rows x 2 columns]

In [18]:
counts= pd.DataFrame(cell_barcodes)

In [19]:
counts

,0,1,2,3,4,5,6,7,8,9,...,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1545,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1546,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,1
1547,0,0,1,0,1,0,0,0,0,0,...,0,0,1,0,3,0,0,0,0,0
1548,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,0,0,0,0,0

In [20]:
counts.index.name='cells'

In [21]:
counts.columns=genes_csv[0]

In [22]:
counts

,1110008F13Rik,1110008P14Rik,1700019D03Rik,1700086L19Rik,2810468N07Rik,2900055J20Rik,2900092D14Rik,3110035E14Rik,3632451O06Rik,6330403K07Rik,...,Zcchc12,Zdhhc24,Zfand6,Zfp57,Zfp637,Zfp975,Zmat4,Zmym1,Znhit3,Znrd1
cells,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1545,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1546,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,1
1547,0,0,1,0,1,0,0,0,0,0,...,0,0,1,0,3,0,0,0,0,0
1548,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,0,0,0,0,0

In [23]:
spatial=sc.AnnData(counts)

/usr/local/lib/python3.10/dist-packages/anndata/_core/aligned_df.py:67: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

In [24]:
spatial

AnnData object with n_obs × n_vars = 1549 × 1020

In [25]:
spatial.obs

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1549 rows x 0 columns]

In [26]:
spatial.obsm["spatial"]=centroids.loc[:,[0,1]].values

In [27]:
spatial.obsm

AxisArrays with keys: spatial

In [28]:
spatial

AnnData object with n_obs × n_vars = 1549 × 1020
    obsm: 'spatial'

In [ ]:
sc_matrix=pd.read_csv('/content/drive/MyDrive/scDatsets/mouse_VISp_2018-06-14_exon-matrix.csv')

In [ ]:
sc_matrix=sc_matrix.drop("Unnamed: 0", axis=1)

In [ ]:
sc_matrix=sc_matrix.T

In [ ]:
sc_matrix

,0,1,2,3,4,5,6,7,8,9,...,45758,45759,45760,45761,45762,45763,45764,45765,45766,45767
F1S4_160108_001_A01,0,0,79,140,0,29,48,0,0,30,...,0,0,0,0,0,0,0,0,0,0
F1S4_160108_001_B01,0,0,121,175,1,23,2,0,181,196,...,0,0,0,0,0,0,0,0,0,0
F1S4_160108_001_C01,0,0,89,68,0,13,28,0,100,75,...,0,0,0,0,0,0,0,0,0,0
F1S4_160108_001_D01,0,0,115,0,0,0,46,0,35,17,...,0,0,0,0,0,0,0,0,0,0
F1S4_160108_001_E01,0,0,390,177,0,41,0,0,0,42,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FYS4_171004_104_D01,0,0,99,160,0,42,0,0,29,0,...,0,0,0,0,0,0,0,0,0,0
FYS4_171004_104_E01,0,0,49,165,0,40,7,0,15,39,...,0,0,0,0,0,0,0,0,0,0
FYS4_171004_104_F01,0,0,123,245,0,0,9,0,0,57,...,0,0,0,0,0,0,0,0,0,0
FYS4_171004_104_G01,0,0,112,179,25,0,0,0,40,40,...,0,0,0,0,0,0,0,0,0,0
FYS4_171004_104_H01,0,0,37,91,0,0,21,0,189,23,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
gene_ids=pd.read_csv('/home/pylab/Desktop/swainasish/Spatial_enhance/datasets/spage_datasets/scRNAseq/Allen_VISp/mouse_VISp_2018-06-14_genes-rows.csv')

In [ ]:
gene_ids

,gene_symbol,gene_id,chromosome,gene_entrez_id,gene_name
0,0610005C13Rik,500717483,7,71661,RIKEN cDNA 0610005C13 gene
1,0610006L08Rik,500717917,7,76253,RIKEN cDNA 0610006L08 gene
2,0610007P14Rik,500730104,12,58520,RIKEN cDNA 0610007P14 gene
3,0610009B22Rik,500726890,11,66050,RIKEN cDNA 0610009B22 gene
4,0610009E02Rik,500702775,2,100125929,RIKEN cDNA 0610009E02 gene
...,...,...,...,...,...
45763,n-R5s142,500721654,8,100861496,nuclear encoded rRNA 5S 142
45764,n-R5s143,500721655,8,100861497,nuclear encoded rRNA 5S 143
45765,n-R5s144,500721656,8,100861498,nuclear encoded rRNA 5S 144
45766,n-R5s146,500721658,8,100861500,nuclear encoded rRNA 5S 146
45767,n-R5s149,500721661,8,100861503,nuclear encoded rRNA 5S 149

In [ ]:
sc_csv=pd.read_csv('/home/pylab/Desktop/swainasish/Spatial_enhance/datasets/spage_datasets/scRNAseq/Allen_VISp/mouse_VISp_2018-06-14_samples-columns.csv')

In [ ]:
sc_csv.columns

Index(['sample_name', 'sample_id', 'sample_type', 'organism', 'donor', 'sex',
       'age_days', 'eye_condition', 'genotype', 'driver_lines',
       'reporter_lines', 'brain_hemisphere', 'brain_region', 'brain_subregion',
       'injection_label_direction', 'injection_primary', 'injection_secondary',
       'injection_tract', 'injection_material',
       'injection_exclusion_criterion', 'facs_date', 'facs_container',
       'facs_sort_criteria', 'rna_amplification_set', 'library_prep_set',
       'library_prep_avg_size_bp', 'seq_name', 'seq_tube', 'seq_batch',
       'total_reads', 'percent_exon_reads', 'percent_intron_reads',
       'percent_intergenic_reads', 'percent_rrna_reads',
       'percent_mt_exon_reads', 'percent_reads_unique', 'percent_synth_reads',
       'percent_ecoli_reads', 'percent_aligned_reads_total', 'complexity_cg',
       'genes_detected_cpm_criterion', 'genes_detected_fpkm_criterion',
       'tdt_cpm', 'gfp_cpm', 'class', 'subclass', 'cluster', 'confusion_score',
       'cluster_correlation', 'core_intermediate_call'],
      dtype='object')

In [ ]:
sc_csv.head(10)

,sample_name,sample_id,sample_type,organism,donor,sex,age_days,eye_condition,genotype,driver_lines,...,genes_detected_cpm_criterion,genes_detected_fpkm_criterion,tdt_cpm,gfp_cpm,class,subclass,cluster,confusion_score,cluster_correlation,core_intermediate_call
0,F1S4_160108_001_A01,527128530,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,10445,9222,248.86,248.86,GABAergic,Vip,Vip Arhgap36 Hmcn1,0.4385,0.837229,Intermediate
1,F1S4_160108_001_B01,527128536,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,11600,10370,289.61,289.61,GABAergic,Lamp5,Lamp5 Lsp1,0.1025,0.878743,Core
2,F1S4_160108_001_C01,527128542,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,11848,10734,281.06,281.06,GABAergic,Lamp5,Lamp5 Lsp1,0.0195,0.887084,Core
3,F1S4_160108_001_D01,527128548,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,9494,8561,390.02,390.02,GABAergic,Vip,Vip Crispld2 Htr2c,0.2734,0.843552,Core
4,F1S4_160108_001_E01,527128554,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,10012,8791,253.92,253.92,GABAergic,Lamp5,Lamp5 Plch2 Dock5,0.7532,0.854994,Core
5,F1S4_160108_001_F01,527128560,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,10696,9145,195.80,195.80,GABAergic,Sst,Sst Tac1 Tacr3,0.4291,0.856063,Core
6,F1S4_160108_001_G01,527128566,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,12692,11724,150.84,150.84,GABAergic,Sncg,Sncg Vip Itih5,0.0599,0.898292,Core
7,F1S4_160108_001_H01,527128572,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,11755,10939,293.20,293.20,GABAergic,Lamp5,Lamp5 Krt73,0.0491,0.893809,Core
8,F1S4_160108_002_A01,527128578,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,10680,9799,284.78,284.78,GABAergic,Vip,Vip Igfbp6 Car10,0.2854,0.827172,Intermediate
9,F1S4_160108_002_B01,527128584,Cells,Mus musculus,225675,M,53,Normal,Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt,Slc32a1-IRES-Cre,...,10420,9197,225.43,225.43,GABAergic,Lamp5,Lamp5 Plch2 Dock5,0.0259,0.855536,Core

In [ ]:
sc_counts=pd.DataFrame(sc_matrix)

In [ ]:
sc_counts.columns=gene_ids['gene_symbol']

In [ ]:
sc_counts

gene_symbol,0610005C13Rik,0610006L08Rik,0610007P14Rik,0610009B22Rik,0610009E02Rik,0610009L18Rik,0610009O20Rik,0610010B08Rik,0610010F05Rik,0610010K14Rik,...,n-R5s134,n-R5s136,n-R5s138,n-R5s139,n-R5s141,n-R5s142,n-R5s143,n-R5s144,n-R5s146,n-R5s149
F1S4_160108_001_A01,0,0,79,140,0,29,48,0,0,30,...,0,0,0,0,0,0,0,0,0,0
F1S4_160108_001_B01,0,0,121,175,1,23,2,0,181,196,...,0,0,0,0,0,0,0,0,0,0
F1S4_160108_001_C01,0,0,89,68,0,13,28,0,100,75,...,0,0,0,0,0,0,0,0,0,0
F1S4_160108_001_D01,0,0,115,0,0,0,46,0,35,17,...,0,0,0,0,0,0,0,0,0,0
F1S4_160108_001_E01,0,0,390,177,0,41,0,0,0,42,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
FYS4_171004_104_D01,0,0,99,160,0,42,0,0,29,0,...,0,0,0,0,0,0,0,0,0,0
FYS4_171004_104_E01,0,0,49,165,0,40,7,0,15,39,...,0,0,0,0,0,0,0,0,0,0
FYS4_171004_104_F01,0,0,123,245,0,0,9,0,0,57,...,0,0,0,0,0,0,0,0,0,0
FYS4_171004_104_G01,0,0,112,179,25,0,0,0,40,40,...,0,0,0,0,0,0,0,0,0,0
FYS4_171004_104_H01,0,0,37,91,0,0,21,0,189,23,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
sc_data=sc.AnnData(sc_counts)

In [ ]:
sc_data.obs

Empty DataFrame
Columns: []
Index: [F1S4_160108_001_A01, F1S4_160108_001_B01, F1S4_160108_001_C01, F1S4_160108_001_D01, F1S4_160108_001_E01, F1S4_160108_001_F01, F1S4_160108_001_G01, F1S4_160108_001_H01, F1S4_160108_002_A01, F1S4_160108_002_B01, F1S4_160108_002_C01, F1S4_160108_002_D01, F1S4_160108_002_E01, F1S4_160108_002_F01, F1S4_160108_002_G01, F1S4_160108_002_H01, F1S4_160108_003_A01, F1S4_160108_003_B01, F1S4_160108_003_C01, F1S4_160108_003_D01, F1S4_160108_003_E01, F1S4_160108_003_F01, F1S4_160108_003_G01, F1S4_160108_003_H01, F1S4_160108_004_A01, F1S4_160108_004_B01, F1S4_160108_004_C01, F1S4_160108_004_D01, F1S4_160108_004_E01, F1S4_160108_004_F01, F1S4_160108_004_G01, F1S4_160108_004_H01, F1S4_160108_005_A01, F1S4_160108_005_B01, F1S4_160108_005_C01, F1S4_160108_005_D01, F1S4_160108_005_E01, F1S4_160108_005_F01, F1S4_160108_005_G01, F1S4_160108_005_H01, F1S4_160108_006_A01, F1S4_160108_006_B01, F1S4_160108_006_C01, F1S4_160108_006_D01, F1S4_160108_006_E01, F1S4_160108_006_F01, F1S4_160108_006_G01, F1S4_160108_006_H01, F1S4_160108_007_A01, F1S4_160108_007_B01, F1S4_160108_007_C01, F1S4_160108_007_D01, F1S4_160108_007_E01, F1S4_160108_007_F01, F1S4_160108_007_G01, F1S4_160108_007_H01, F1S4_160108_008_A01, F1S4_160108_008_B01, F1S4_160108_008_C01, F1S4_160108_008_D01, F1S4_160108_008_E01, F1S4_160108_008_F01, F1S4_160108_008_G01, F1S4_160108_008_H01, F1S4_160108_009_A01, F1S4_160108_009_B01, F1S4_160108_009_C01, F1S4_160108_009_D01, F1S4_160108_009_E01, F1S4_160108_009_F01, F1S4_160108_009_G01, F1S4_160108_009_H01, F1S4_160108_010_A01, F1S4_160108_010_B01, F1S4_160108_010_C01, F1S4_160108_010_D01, F1S4_160108_010_E01, F1S4_160108_010_F01, F1S4_160108_010_G01, F1S4_160108_010_H01, F1S4_160108_011_A01, F1S4_160108_011_B01, F1S4_160108_011_C01, F1S4_160108_011_D01, F1S4_160108_011_E01, F1S4_160108_011_F01, F1S4_160108_011_G01, F1S4_160108_011_H01, F1S4_160108_012_A01, F1S4_160108_012_B01, F1S4_160108_012_C01, F1S4_160108_012_D01, F1S4_160108_012_E01, F1S4_160108_012_F01, F1S4_160108_012_G01, F1S4_160108_012_H01, F1S4_160108_013_A01, F1S4_160108_013_B01, F1S4_160108_013_C01, F1S4_160108_013_D01, ...]

[15413 rows x 0 columns]

In [ ]:
sc_data.var

Empty DataFrame
Columns: []
Index: [0610005C13Rik, 0610006L08Rik, 0610007P14Rik, 0610009B22Rik, 0610009E02Rik, 0610009L18Rik, 0610009O20Rik, 0610010B08Rik, 0610010F05Rik, 0610010K14Rik, 0610011F06Rik, 0610012G03Rik, 0610025J13Rik, 0610030E20Rik, 0610031O16Rik, 0610037L13Rik, 0610038B21Rik, 0610039H22Rik, 0610039K10Rik, 0610040B10Rik, 0610040F04Rik, 0610040J01Rik, 0610043K17Rik, 1010001N08Rik, 1100001I12Rik, 1110001J03Rik, 1110002J07Rik, 1110002L01Rik, 1110002O04Rik, 1110004E09Rik, 1110004F10Rik, 1110006O24Rik, 1110007C09Rik, 1110008F13Rik, 1110008L16Rik, 1110008P14Rik, 1110012L19Rik, 1110015O18Rik, 1110017D15Rik, 1110018N20Rik, 1110019D14Rik, 1110020A21Rik, 1110025L11Rik, 1110028F11Rik, 1110028F18Rik, 1110032A03Rik, 1110032F04Rik, 1110034G24Rik, 1110036E04Rik, 1110037F02Rik, 1110038B12Rik, 1110038F14Rik, 1110046J04Rik, 1110051M20Rik, 1110054M08Rik, 1110057K04Rik, 1110057P08Rik, 1110058D11Rik, 1110058L19Rik, 1110059E24Rik, 1110059G10Rik, 1110065P20Rik, 1190002F15Rik, 1190002N15Rik, 1190003K10Rik, 1190005I06Rik, 1190007I07Rik, 1190028D05Rik, 1200014J11Rik, 1300002E11Rik, 1300017J02Rik, 1500002F19Rik, 1500004A13Rik, 1500009C09Rik, 1500009L16Rik, 1500011B03Rik, 1500011K16Rik, 1500012F01Rik, 1500012K07Rik, 1500015A07Rik, 1500015L24Rik, 1500015O10Rik, 1500017E21Rik, 1500026H17Rik, 1500035N22Rik, 1520401A03Rik, 1600002D24Rik, 1600002H07Rik, 1600002K03Rik, 1600010M07Rik, 1600012H06Rik, 1600014C10Rik, 1600014C23Rik, 1600014K23Rik, 1600015I10Rik, 1600019K03Rik, 1600020E01Rik, 1600023N17Rik, 1600025M17Rik, 1600027J07Rik, ...]

[45768 rows x 0 columns]

In [ ]:
sc_data.obs['class']=(sc_csv['class'].to_numpy())

In [ ]:
sc_data.obs['subclass']= sc_csv['subclass'].to_numpy()

In [ ]:
sc_data.obs

                             class  subclass
F1S4_160108_001_A01      GABAergic       Vip
F1S4_160108_001_B01      GABAergic     Lamp5
F1S4_160108_001_C01      GABAergic     Lamp5
F1S4_160108_001_D01      GABAergic       Vip
F1S4_160108_001_E01      GABAergic     Lamp5
...                            ...       ...
FYS4_171004_104_D01      GABAergic       Sst
FYS4_171004_104_E01       No Class  No Class
FYS4_171004_104_F01  Glutamatergic     L5 PT
FYS4_171004_104_G01      GABAergic       Sst
FYS4_171004_104_H01      GABAergic     Pvalb

[15413 rows x 2 columns]

In [ ]:
sc_data.var= gene_ids.iloc[:, 0:]

In [ ]:
sc_data.var

,gene_symbol,gene_id,chromosome,gene_entrez_id,gene_name
0,0610005C13Rik,500717483,7,71661,RIKEN cDNA 0610005C13 gene
1,0610006L08Rik,500717917,7,76253,RIKEN cDNA 0610006L08 gene
2,0610007P14Rik,500730104,12,58520,RIKEN cDNA 0610007P14 gene
3,0610009B22Rik,500726890,11,66050,RIKEN cDNA 0610009B22 gene
4,0610009E02Rik,500702775,2,100125929,RIKEN cDNA 0610009E02 gene
...,...,...,...,...,...
45763,n-R5s142,500721654,8,100861496,nuclear encoded rRNA 5S 142
45764,n-R5s143,500721655,8,100861497,nuclear encoded rRNA 5S 143
45765,n-R5s144,500721656,8,100861498,nuclear encoded rRNA 5S 144
45766,n-R5s146,500721658,8,100861500,nuclear encoded rRNA 5S 146
45767,n-R5s149,500721661,8,100861503,nuclear encoded rRNA 5S 149

In [ ]:
sc_data.var.index= sc_data.var['gene_symbol']

In [ ]:
sc_data.var

,gene_symbol,gene_id,chromosome,gene_entrez_id,gene_name
gene_symbol,,,,,
0610005C13Rik,0610005C13Rik,500717483,7,71661,RIKEN cDNA 0610005C13 gene
0610006L08Rik,0610006L08Rik,500717917,7,76253,RIKEN cDNA 0610006L08 gene
0610007P14Rik,0610007P14Rik,500730104,12,58520,RIKEN cDNA 0610007P14 gene
0610009B22Rik,0610009B22Rik,500726890,11,66050,RIKEN cDNA 0610009B22 gene
0610009E02Rik,0610009E02Rik,500702775,2,100125929,RIKEN cDNA 0610009E02 gene
...,...,...,...,...,...
n-R5s142,n-R5s142,500721654,8,100861496,nuclear encoded rRNA 5S 142
n-R5s143,n-R5s143,500721655,8,100861497,nuclear encoded rRNA 5S 143
n-R5s144,n-R5s144,500721656,8,100861498,nuclear encoded rRNA 5S 144
n-R5s146,n-R5s146,500721658,8,100861500,nuclear encoded rRNA 5S 146
n-R5s149,n-R5s149,500721661,8,100861503,nuclear encoded rRNA 5S 149

In [ ]:
sc_data.var=sc_data.var.drop('gene_symbol', axis=1)

In [ ]:
sc_data.var

,gene_id,chromosome,gene_entrez_id,gene_name
gene_symbol,,,,
0610005C13Rik,500717483,7,71661,RIKEN cDNA 0610005C13 gene
0610006L08Rik,500717917,7,76253,RIKEN cDNA 0610006L08 gene
0610007P14Rik,500730104,12,58520,RIKEN cDNA 0610007P14 gene
0610009B22Rik,500726890,11,66050,RIKEN cDNA 0610009B22 gene
0610009E02Rik,500702775,2,100125929,RIKEN cDNA 0610009E02 gene
...,...,...,...,...
n-R5s142,500721654,8,100861496,nuclear encoded rRNA 5S 142
n-R5s143,500721655,8,100861497,nuclear encoded rRNA 5S 143
n-R5s144,500721656,8,100861498,nuclear encoded rRNA 5S 144
n-R5s146,500721658,8,100861500,nuclear encoded rRNA 5S 146
n-R5s149,500721661,8,100861503,nuclear encoded rRNA 5S 149

In [ ]:
sc_data

AnnData object with n_obs × n_vars = 15413 × 45768
    obs: 'class', 'subclass'
    var: 'gene_id', 'chromosome', 'gene_entrez_id', 'gene_name'

## Preparing for stPlus

In [ ]:
sc.pp.normalize_total(sc_data)
sc.pp.log1p(sc_data)
sc.pp.normalize_total(spatial)
sc.pp.log1p(spatial)

WARNING: adata.X seems to be already log-transformed.
WARNING: adata.X seems to be already log-transformed.

In [ ]:
spatial_df = pd.DataFrame(spatial.X, columns=spatial.var.index.values)
scrna_df   = pd.DataFrame(sc_data.X, columns=sc_data.var.index.values)

In [ ]:
spatial_df

,1110008F13Rik,1110008P14Rik,1700019D03Rik,1700086L19Rik,2810468N07Rik,2900055J20Rik,2900092D14Rik,3110035E14Rik,3632451O06Rik,6330403K07Rik,...,Zcchc12,Zdhhc24,Zfand6,Zfp57,Zfp637,Zfp975,Zmat4,Zmym1,Znhit3,Znrd1
0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00000
1,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.836035,0.0,0.0,0.0,0.0,0.00000
2,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.824573,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00000
3,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.523002,0.000000,0.0,0.0,0.0,0.0,0.00000
4,0.0,0.0,0.000000,0.519737,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.616147,0.0,0.0,0.0,0.0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1544,0.0,0.0,0.629607,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.00000
1545,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.515474,0.0,0.0,0.0,0.0,0.00000
1546,0.0,0.0,0.351480,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.409649,0.0,0.0,0.0,0.0,0.35148
1547,0.0,0.0,0.346713,0.000000,0.346713,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.346713,0.000000,0.437339,0.0,0.0,0.0,0.0,0.00000
1548,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.477562,0.0,0.0,0.0,0.0,0.00000

In [ ]:
print(spatial_df['1110008F13Rik'])

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1544    0.0
1545    0.0
1546    0.0
1547    0.0
1548    0.0
Name: 1110008F13Rik, Length: 1549, dtype: float32

In [ ]:
scrna_df

,0610005C13Rik,0610006L08Rik,0610007P14Rik,0610009B22Rik,0610009E02Rik,0610009L18Rik,0610009O20Rik,0610010B08Rik,0610010F05Rik,0610010K14Rik,...,n-R5s134,n-R5s136,n-R5s138,n-R5s139,n-R5s141,n-R5s142,n-R5s143,n-R5s144,n-R5s146,n-R5s149
0,0.0,0.0,1.691218,1.792684,0.000000,1.487022,1.594336,0.0,0.000000,1.494562,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.668022,1.729927,0.452576,1.335763,0.654034,0.0,1.735404,1.748227,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.582771,1.532670,0.000000,1.166055,1.349661,0.0,1.603766,1.551178,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.761726,0.000000,0.000000,0.000000,1.577386,0.0,1.516048,1.337598,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.973399,1.851390,0.000000,1.579604,0.000000,0.0,0.000000,1.584676,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15408,0.0,0.0,1.971297,2.048912,0.000000,1.816442,0.000000,0.0,1.741945,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15409,0.0,0.0,1.639467,1.843293,0.000000,1.601228,1.207956,0.0,1.395513,1.596362,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15410,0.0,0.0,2.033525,2.140092,0.000000,0.000000,1.491717,0.0,0.000000,1.899957,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15411,0.0,0.0,1.894423,1.968048,1.616948,0.000000,0.000000,0.0,1.711836,1.711836,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15412,0.0,0.0,1.839645,2.002374,0.000000,0.000000,1.722964,0.0,2.118043,1.742553,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
raw_shared_gene = np.intersect1d(spatial_df.columns, scrna_df.columns)

In [ ]:
print(raw_shared_gene)

['1110008F13Rik' '1110008P14Rik' '1700019D03Rik' '1700086L19Rik'
 '2810468N07Rik' '2900055J20Rik' '2900092D14Rik' '3110035E14Rik'
 '3632451O06Rik' '6330403K07Rik' '9130024F11Rik' '9430021M05Rik'
 'A730017C20Rik' 'A830018L16Rik' 'AW549877' 'Aamp' 'Abat' 'Abhd3' 'Acat2'
 'Ackr1' 'Acot13' 'Acrbp' 'Acsbg1' 'Acss1' 'Acta1' 'Acta2' 'Acvr1c'
 'Adamts18' 'Adamts2' 'Adamts3' 'Adarb2' 'Adcyap1' 'Adk' 'Adm' 'Adrbk2'
 'Aebp1' 'Afap1' 'Agrp' 'Agt' 'Agtr1a' 'Aif1' 'Ak1' 'Ak5' 'Akr1c18'
 'Akr1e1' 'Aldh1l1' 'Aldh3a2' 'Aldoc' 'Alkbh5' 'Amph' 'Anapc13' 'Ankrd29'
 'Ano3' 'Anxa5' 'Apod' 'Apoe' 'Aprt' 'Aqp4' 'Arc' 'Arf5' 'Arhgap24'
 'Arhgap25' 'Arl4a' 'Arl4d' 'Arpc2' 'Arpc3' 'Arpp19' 'Arpp21' 'Arx'
 'Asb11' 'Ascl1' 'Ass1' 'Atp1a2' 'Atp1b2' 'Atp2b4' 'Atp6ap1l' 'Atp6v0e'
 'Atp9a' 'Atraid' 'Avp' 'B230216N24Rik' 'B2m' 'B3galt2' 'Bace2' 'Baiap2'
 'Batf3' 'Bc1' 'Bcan' 'Bcap29' 'Bcar3' 'Bcl6' 'Bdnf' 'Bex1' 'Bglap3'
 'Bhlhe40' 'Blnk' 'Bmp3' 'Brinp3' 'Bsg' 'Btbd10' 'Btbd11' 'Btbd3' 'Btg2'
 'C1ql3' 'C1qtnf7' 'C730002L08Rik' 'Cacng3' 'Cacng4' 'Cadps2' 'Calb1'
 'Calb2' 'Calca' 'Caln1' 'Camk2a' 'Camk2d' 'Camk2n1' 'Camk4' 'Car10'
 'Car12' 'Car2' 'Car4' 'Cartpt' 'Cav1' 'Cbln2' 'Cbln4' 'Ccar2' 'Ccdc109b'
 'Ccdc80' 'Cck' 'Cd164' 'Cd200' 'Cd302' 'Cd34' 'Cd63' 'Cd7' 'Cd9' 'Cdca7'
 'Cdh13' 'Cdh18' 'Cdh9' 'Cdk4' 'Cdk6' 'Cend1' 'Cenpw' 'Chat' 'Chchd3'
 'Chl1' 'Chodl' 'Chrm2' 'Chrna2' 'Chrna6' 'Chrnb3' 'Cidea' 'Cited1'
 'Cldn10' 'Cldn5' 'Clic1' 'Cmtm5' 'Cnih3' 'Cnot6l' 'Cnp' 'Cnr1' 'Cntn4'
 'Cntn6' 'Cntnap4' 'Coch' 'Col14a1' 'Col25a1' 'Col6a1' 'Commd3' 'Coro6'
 'Cort' 'Cox20' 'Cox6a2' 'Cplx1' 'Cplx3' 'Cpne2' 'Cpne4' 'Cpne5' 'Cpne6'
 'Cpne7' 'Cpne9' 'Crh' 'Crhbp' 'Crip2' 'Crispld2' 'Cryab' 'Crym' 'Csrnp1'
 'Ctgf' 'Ctso' 'Ctsz' 'Ctxn1' 'Ctxn3' 'Cux2' 'Cxcl14' 'Cxxc4' 'Cyb561'
 'Cyb5r1' 'Cyb5r2' 'Cygb' 'Cyp2j9' 'Cyr61' 'Dbi' 'Dbpht2' 'Dcdc2c' 'Dcn'
 'Ddah1' 'Ddit3' 'Ddit4l' 'Ddt' 'Depdc7' 'Deptor' 'Dgkb' 'Dgkg' 'Dhrs3'
 'Dkk3' 'Dkkl1' 'Dlx1' 'Dlx2' 'Dlx5' 'Dlx6os1' 'Dnaja2' 'Dnajc15' 'Dner'
 'Dok5' 'Dtwd1' 'Dusp1' 'Dusp14' 'Dusp6' 'Dync1i1' 'Dync2li1' 'Dynlt3'
 'E430025E21Rik' 'Ednrb' 'Eef1e1' 'Eepd1' 'Efemp1' 'Efhd2' 'Efna1' 'Efna5'
 'Efr3a' 'Egln3' 'Egr1' 'Egr2' 'Egr3' 'Egr4' 'Eid1' 'Eif4e' 'Elavl2'
 'Elfn1' 'Elmo1' 'Elovl1' 'Elovl5' 'Elp3' 'Enc1' 'Enpp2' 'Epha4' 'Epha7'
 'Ephx2' 'Ephx4' 'Esd' 'Etv1' 'Etv5' 'Exosc9' 'F3' 'Fabp7' 'Fam107a'
 'Fam131a' 'Fam134a' 'Fam163b' 'Fam19a1' 'Fam19a2' 'Fam3c' 'Fam46a'
 'Fam81a' 'Fam84a' 'Fam84b' 'Fbxl3' 'Fbxo11' 'Fbxo44' 'Fbxw11' 'Fdft1'
 'Fezf2' 'Fgf12' 'Fgfr3' 'Fkbp1a' 'Flrt3' 'Fmnl1' 'Fmo1' 'Fos' 'Fosb'
 'Fosl1' 'Fosl2' 'Foxp1' 'Foxp2' 'Frem1' 'Frmd7' 'Frmpd3' 'Fst' 'Fstl5'
 'Fto' 'Fut9' 'Fxyd1' 'Fxyd6' 'Fxyd7' 'Gaa' 'Gabra5' 'Gabrd' 'Gabrg1'
 'Gad1' 'Gad2' 'Gadd45a' 'Galnt14' 'Galntl6' 'Gap43' 'Garnl3' 'Gatm' 'Gda'
 'Gde1' 'Gemin7' 'Gfap' 'Gfra2' 'Gja1' 'Gjb6' 'Glt8d2' 'Glul' 'Gm11549'
 'Gm13629' 'Gm15881' 'Gm2a' 'Gm5643' 'Gm765' 'Gmppa' 'Gmpr' 'Gnai1' 'Gnb5'
 'Gng7' 'Gpc3' 'Gpd1' 'Gpm6b' 'Gpr151' 'Gpr22' 'Gpr3' 'Gpr37l1' 'Gpr88'
 'Gprasp2' 'Gpx1' 'Gpx3' 'Gria1' 'Gria3' 'Grik1' 'Grm3' 'Grp' 'Grpr' 'Gsn'
 'Gss' 'Gsta4' 'Gstm1' 'Gstm5' 'Gstm6' 'Gucy1b3' 'Hadhb' 'Hapln1' 'Has2'
 'Hax1' 'Hcrtr1' 'Hcrtr2' 'Hdac9' 'Hddc2' 'Herc3' 'Hhatl' 'Hlf' 'Hmgcr'
 'Hmgcs1' 'Hmgn1' 'Hn1' 'Hnrnph2' 'Homer1' 'Hpca' 'Hpcal1' 'Hpcal4'
 'Hs3st1' 'Hs3st4' 'Hsd11b1' 'Hsd17b12' 'Hsd3b7' 'Hspa2' 'Hspd1' 'Htr2a'
 'Htr3a' 'Htr5b' 'Htra1' 'Id2' 'Id3' 'Idi1' 'Ifi27' 'Ifit2' 'Ifit3'
 'Ifitm2' 'Igf1' 'Igfbp4' 'Igfbp6' 'Igsf3' 'Igtp' 'Il1rapl2' 'Immp1l'
 'Ina' 'Inhba' 'Inpp4b' 'Insl6' 'Ipcef1' 'Isca2' 'Itih5' 'Itm2a' 'Itm2c'
 'Junb' 'Kcna1' 'Kcnab1' 'Kcnc2' 'Kcnip1' 'Kcnip2' 'Kcnip3' 'Kcnk2'
 'Kcnmb4' 'Kcns3' 'Kcnv1' 'Kctd4' 'Kctd6' 'Kctd8' 'Kif5a' 'Kifc2' 'Kit'
 'Klf10' 'Klhl13' 'Klhl14' 'Klhl5' 'Klk8' 'Krt12' 'Krt18' 'Krt73' 'Lamp5'
 'Lamtor5' 'Laptm4a' 'Laptm4b' 'Lcat' 'Ldb2' 'Lgals1' 'Lgmn' 'Lhfpl3'
 'Lhfpl5' 'Lhx1' 'Lhx6' 'Lims2' 'Lin7b' 'Lipg' 'Lman1l' 'Lmcd1' 'Lmo2'
 'Lmo3' 'Lmo4' 'Lpar1' 'Lrrc4c' 'Lrrc61' 'Lrrtm4' 'Luzp2' 'Lxn' 'Ly6d'
 'Ly6e' 'Ly6g6e' 'Lypd1' 'Lypd6' 'Lypd6b' 'Mab21l1' 'Maf' 'Mal' 'Mal2'
 'Man1a' 'Map2k1' 'Mapk3' 'Mapre2' 'Marcks' 'Mas1' 'Mat2b' 'Matn2' 'Mbp'
 'Mc4r' 'Mcee' 'Mcts1' 'Mdga1' 'Med10' 'Med21' 'Mef2c' 'Megf10' 'Mei1'
 'Mettl14' 'Mettl23' 'Mettl3' 'Mfge8' 'Mgat4c' 'Mgp' 'Mia' 'Micu1' 'Mien1'
 'Mmd2' 'Mmp16' 'Mobp' 'Mospd1' 'Mpi' 'Mrap2' 'Mrpl13' 'Mrpl22' 'Mrpl33'
 'Mrps18c' 'Mrps28' 'Mrps5' 'Msantd2' 'Msmo1' 'Mt1' 'Mt2' 'Mtfp1' 'Mybpc1'
 'Myh1' 'Myh4' 'Myh8' 'Myl4' 'Mylk' 'Myo1c' 'Myo5b' 'Naa38' 'Ncdn' 'Ncoa7'
 'Ndfip1' 'Ndn' 'Ndnf' 'Ndrg2' 'Ndst4' 'Ndufaf2' 'Ndufb2' 'Ndufs1'
 'Ndufs2' 'Necab3' 'Nefl' 'Nek7' 'Nell1' 'Nell2' 'Neurod1' 'Neurod2'
 'Neurod6' 'Neurog2' 'Nfia' 'Nfib' 'Ngb' 'Ngf' 'Nipsnap3b' 'Nkain4'
 'Nkx2-1' 'Nnat' 'Nos1' 'Nov' 'Npas1' 'Npas4' 'Npdc1' 'Nptx1' 'Nptx2'
 'Npy' 'Npy2r' 'Nr1d1' 'Nr2f2' 'Nr4a1' 'Nr4a2' 'Nr5a1' 'Nrep' 'Nrg1'
 'Nrgn' 'Nrip2' 'Nrip3' 'Nrm' 'Nrn1' 'Nrp1' 'Nrsn1' 'Nrsn2' 'Nts' 'Ntsr1'
 'Ntsr2' 'Nudt2' 'Nudt4' 'Nxph1' 'Nxph2' 'Nxph4' 'Obox3' 'Ogfrl1' 'Olfm3'
 'Oprm1' 'Osbpl1a' 'Osgin2' 'Otof' 'Otub2' 'Oxt' 'Pacsin2' 'Palmd' 'Pamr1'
 'Pantr1' 'Papss1' 'Parm1' 'Pax6' 'Pbx3' 'Pcbd1' 'Pcdh15' 'Pcdh8' 'Pcdha1'
 'Pcdha10' 'Pcdha11' 'Pcdha12' 'Pcdha2' 'Pcdha3' 'Pcdha5' 'Pcdha7'
 'Pcdha8' 'Pcdha9' 'Pcdhac1' 'Pcdhac2' 'Pcdhb1' 'Pcdhb10' 'Pcdhb11'
 'Pcdhb12' 'Pcdhb14' 'Pcdhb15' 'Pcdhb17' 'Pcdhb18' 'Pcdhb19' 'Pcdhb2'
 'Pcdhb20' 'Pcdhb3' 'Pcdhb4' 'Pcdhb5' 'Pcdhb6' 'Pcdhb7' 'Pcdhb8' 'Pcdhb9'
 'Pcdhga10' 'Pcdhga12' 'Pcdhga2' 'Pcdhga3' 'Pcdhga5' 'Pcdhga6' 'Pcdhga7'
 'Pcdhga8' 'Pcdhga9' 'Pcp4' 'Pcp4l1' 'Pcsk2' 'Pcsk5' 'Pde11a' 'Pde1a'
 'Pde1c' 'Pdgfra' 'Pdia4' 'Pdlim1' 'Pdlim3' 'Pdp1' 'Pdxk' 'Pdyn' 'Pdzrn3'
 'Pea15a' 'Penk' 'Per3' 'Pfdn4' 'Pfkl' 'Pfn1' 'Pgm2l1' 'Pgr' 'Phactr1'
 'Phkg2' 'Phlda1' 'Phyhip' 'Pip5k1b' 'Pitpnc1' 'Pkig' 'Pla2g4a' 'Pla2g7'
 'Plb1' 'Plcxd2' 'Plcxd3' 'Plekhb1' 'Plk2' 'Pllp' 'Plp1' 'Pls3' 'Pmp22'
 'Pnck' 'Pnoc' 'Pnpo' 'Polr2h' 'Pon2' 'Pou3f4' 'Ppa2' 'Ppil3' 'Ppm1h'
 'Ppp1r1b' 'Ppp1r3c' 'Ppp3cb' 'Prc1' 'Prdx4' 'Prdx6' 'Prkcg' 'Prlr'
 'Prmt2' 'Prok2' 'Prss22' 'Prss23' 'Psat1' 'Psma4' 'Psmb4' 'Ptchd1'
 'Ptchd2' 'Pter' 'Ptgds' 'Ptgfr' 'Ptgs2' 'Pthlh' 'Ptk2' 'Ptk2b' 'Ptn'
 'Ptpn2' 'Ptprk' 'Ptprz1' 'Pvalb' 'Qk' 'Qpct' 'Qrfpr' 'Rab15' 'Rab26'
 'Rab27b' 'Rab31' 'Rab3b' 'Rab3c' 'Rab7' 'Rac1' 'Ralyl' 'Ramp3' 'Rap1gds1'
 'Rapgef6' 'Rasgef1b' 'Rasgrf1' 'Rasgrf2' 'Rasgrp1' 'Rasl11a' 'Rbfox3'
 'Rbm18' 'Rbp4' 'Rcan2' 'Reln' 'Rerg' 'Resp18' 'Rfc2' 'Rgs10' 'Rgs12'
 'Rgs2' 'Rgs4' 'Rgs8' 'Rgs9' 'Rhebl1' 'Rit2' 'Rlbp1' 'Rln1' 'Rnd2' 'Rnd3'
 'Rnf13' 'Rnh1' 'Rorb' 'Rpp21' 'Rpp25' 'Rprm' 'Rps12' 'Rps2' 'Rsph9'
 'Rspo1' 'Rspo2' 'Rwdd2a' 'S100a1' 'S100a10' 'S100a16' 'S100b' 'S1pr1'
 'Sat1' 'Satb2' 'Sc5d' 'Sccpdh' 'Scd2' 'Scg2' 'Scg3' 'Scml4' 'Scnn1a'
 'Scrg1' 'Sdc4' 'Sdcbp' 'Sec11c' 'Selm' 'Sema3c' 'Sema3e' 'Sema5b' 'Sepp1'
 'Sept4' 'Serpinb11' 'Serpine1' 'Serpine2' 'Serpini1' 'Sgk1' 'Sgpp2'
 'Sh3bgrl' 'Sh3bgrl3' 'Sirt2' 'Sirt3' 'Skap1' 'Skil' 'Sla' 'Slc17a6'
 'Slc17a7' 'Slc18a3' 'Slc1a1' 'Slc1a2' 'Slc1a3' 'Slc20a1' 'Slc24a2'
 'Slc25a11' 'Slc25a17' 'Slc25a18' 'Slc25a36' 'Slc2a13' 'Slc30a9' 'Slc32a1'
 'Slc38a3' 'Slc50a1' 'Slc5a5' 'Slc5a7' 'Slc6a1' 'Slc6a11' 'Slc6a15'
 'Slc7a3' 'Slc7a4' 'Slco1c1' 'Sln' 'Smad3' 'Smim18' 'Smim8' 'Snca' 'Sncg'
 'Snhg4' 'Snrpb2' 'Snrpe' 'Snrpg' 'Snurf' 'Snx10' 'Sorcs3' 'Sostdc1'
 'Sox2ot' 'Sox6' 'Sox9' 'Sp8' 'Sp9' 'Sparc' 'Sparcl1' 'Spink8' 'Spint2'
 'Spock3' 'Spon1' 'Spp1' 'Spry4' 'Sst' 'Sstr2' 'Sstr4' 'St3gal5' 'St3gal6'
 'St6galnac5' 'Stac' 'Stat4' 'Stmn4' 'Stx12' 'Stx1a' 'Sulf2' 'Sult2b1'
 'Sv2b' 'Syn1' 'Syndig1' 'Syndig1l' 'Synpr' 'Syt10' 'Syt17' 'Syt6' 'Tac1'
 'Tac2' 'Tacc1' 'Tacr1' 'Tacr3' 'Tacstd2' 'Tbr1' 'Tceal1' 'Tceal5'
 'Tcerg1l' 'Teddm3' 'Tenm2' 'Th' 'Thrsp' 'Thsd7a' 'Thsd7b' 'Thumpd3'
 'Timm8a1' 'Timp3' 'Timp4' 'Tle4' 'Tm7sf2' 'Tmbim6' 'Tmeff1' 'Tmeff2'
 'Tmem100' 'Tmem130' 'Tmem132c' 'Tmem159' 'Tmem176a' 'Tmem176b' 'Tmem179b'
 'Tmem215' 'Tmem258' 'Tmem55a' 'Tmem60' 'Tmem91' 'Tmem97' 'Tmsb10' 'Tmtc4'
 'Tmx1' 'Tnfaip6' 'Tnfaip8l3' 'Tnfrsf12a' 'Tnmd' 'Tnni3k' 'Tomm22' 'Tox'
 'Tox3' 'Tpbg' 'Tpd52l1' 'Tph2' 'Tpm1' 'Tpm2' 'Traip' 'Trap1' 'Trappc1'
 'Trappc2l' 'Trf' 'Trim32' 'Trp53i11' 'Trpv6' 'Tsc22d1' 'Tsc22d3' 'Tshz2'
 'Tsnax' 'Tspan12' 'Tspan13' 'Tspan6' 'Ttyh1' 'Tuba8' 'Tubb4b' 'Tusc3'
 'Twistnb' 'Uap1' 'Ube2e3' 'Ucma' 'Ucp2' 'Ugdh' 'Urod' 'Usp46' 'Vamp1'
 'Vgf' 'Vip' 'Vsig2' 'Vstm2a' 'Wdpcp' 'Wfs1' 'Whrn' 'Wls' 'Wsb2' 'Wt1'
 'Ythdc1' 'Ythdc2' 'Ythdf1' 'Ythdf2' 'Ythdf3' 'Zcchc12' 'Zdhhc24' 'Zfand6'
 'Zfp57' 'Zfp637' 'Zmat4' 'Zmym1' 'Znhit3' 'Znrd1']

In [ ]:
raw_shared_gene.shape

(996,)

In [ ]:
for x in spatial_df.columns:
    if x not in raw_shared_gene:
        print(x)

Adgra1
Adgrg6
Adgrl2
BFP
Cre
Eef1akmt1
eRNA1
eRNA2
eRNA3
eRNA4
eRNA5
EYFP
Flpo
Hacd3
mCherry
mTFP
Nat8f1
Nectin3
Nectin4
Plpp3
Plpp4
Rida
Sdhaf4
Zfp975

In [ ]:
from sklearn.model_selection import LeaveOneOut
import torch
from stPlus import *

In [ ]:
loo = LeaveOneOut()
loo.get_n_splits(raw_shared_gene)
torch.manual_seed(10)
idx = 1

In [ ]:
for train_ind, test_ind in loo.split(raw_shared_gene):
    print("\n===== Fold %d =====\nNumber of train genes: %d, Number of test genes: %d" % (idx, len(train_ind), len(test_ind)))
    train_gene = raw_shared_gene[train_ind]
    test_gene  = raw_shared_gene[test_ind]
#     print(train_gene)
#     print(test_gene)
    test_spatial_df =spatial_df[test_gene]
    print(test_spatial_df)
    spatial_df_train = spatial_df[train_gene]

    if idx == 1:
        all_pred_res = pd.DataFrame(np.zeros((spatial_df.shape[0], raw_shared_gene.shape[0])), columns=raw_shared_gene)
    save_path_prefix = './model/stPlus-demo-fold%d' % (idx)
    stPlus_res = stPlus(spatial_df, scrna_df, test_gene, save_path_prefix)
    all_pred_res[stPlus_res.columns.values] = stPlus_res
    idx += 1

===== Fold 997 =====
Number of train genes: 995, Number of test genes: 1
      1110008F13Rik
0               0.0
1               0.0
2               0.0
3               0.0
4               0.0
...             ...
1544            0.0
1545            0.0
1546            0.0
1547            0.0
1548            0.0

[1549 rows x 1 columns]
Models will be saved in: ./model/stPlus-demo-fold997-5min*.pt

Spatial transcriptomics data: 1549 cells * 1020 genes
Reference scRNA-seq data:     15413 cells * 45768 genes
1 genes to be predicted

Start initialization